[package]
name = "tnum"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "test_mul"
path = "src/tnum_mul.rs"

[[bin]]
name = "compare"
path = "src/compare.rs"